export const womanProducts = [
  {
    id: "w1",
    name: "Draped Asymmetric Top",
    price: "49.90 USD",
    image: "/models/female/image copy 5.png",
    colors: ["#f5f0e8", "#2c2c2c"],
    isNew: true,
    category: "Tops",
  },
  {
    id: "w2",
    name: "Oversized Wool Blend Coat",
    price: "199.00 USD",
    image: "/models/female/image copy 2.png",
    colors: ["#1a1a2e", "#8b7355"],
    isNew: false,
    category: "Coats",
  },
  {
    id: "w3",
    name: "Soft Knit Mock Neck",
    price: "35.90 USD",
    image: "/models/female/image copy 3.png",
    colors: ["#f5f0e8", "#2c2c2c", "#8b7355"],
    isNew: false,
    category: "Knitwear",
  },
  {
    id: "w4",
    name: "High-Rise Tailored Trousers",
    price: "69.90 USD",
    image: "/models/female/image copy 6.png",
    colors: ["#2c2c2c", "#1a1a2e", "#6b7280"],
    isNew: true,
    category: "Trousers",
  },
  {
    id: "w5",
    name: "Satin Finish Midi Dress",
    price: "89.90 USD",
    image: "/models/female/image copy 7.png",
    colors: ["#d4a574", "#2c2c2c"],
    isNew: false,
    category: "Dresses",
  },
  {
    id: "w6",
    name: "Oversized Poplin Shirt",
    price: "45.90 USD",
    image: "/models/female/image.png",
    colors: ["#ffffff", "#f5f0e8"],
    isNew: false,
    category: "Tops",
  },
  {
    id: "w7",
    name: "Ribbed Knit Dress",
    price: "59.90 USD",
    image: "/models/female/image copy.png",
    colors: ["#f5f0e8"],
    isNew: true,
    category: "Dresses",
  },
  {
    id: "w8",
    name: "Leather Ankle Boots",
    price: "159.00 USD",
    image: "/models/female/image copy 4.png",
    colors: ["#2c2c2c"],
    isNew: false,
    category: "Shoes",
  },
];

export const manProducts = [
  {
    id: "m1",
    name: "Oversized Wool Coat",
    price: "135.00 USD",
    image: "/models/males/image copy.png",
    colors: ["#2c2c2c", "#1a1a2e"],
    isNew: false,
    category: "Coats",
  },
  {
    id: "m2",
    name: "Textured Knit Sweater",
    price: "55.90 USD",
    image: "/models/males/image copy 2.png",
    colors: ["#d4c9b0", "#2c2c2c"],
    isNew: false,
    category: "Knitwear",
  },
  {
    id: "m3",
    name: "Technical Jogger SL1",
    price: "89.90 USD",
    image: "/models/males/image copy 3.png",
    colors: ["#3d4a5c", "#2c2c2c"],
    isNew: true,
    category: "Trousers",
  },
  {
    id: "m4",
    name: "Charcoal Slim Suit",
    price: "249.00 USD",
    image: "/models/males/image copy 4.png",
    colors: ["#3d3d3d", "#1a1a2e"],
    isNew: false,
    category: "Suits",
  },
  {
    id: "m5",
    name: "Wide Leg Trousers SL1",
    price: "49.90 USD",
    image: "/models/males/image copy 5.png",
    colors: ["#f5f0e8", "#2c2c2c"],
    isNew: false,
    category: "Trousers",
  },
  {
    id: "m6",
    name: "Nappa Leather Jacket",
    price: "199.00 USD",
    image: "/models/males/image.png",
    colors: ["#3d2b1f", "#2c2c2c"],
    isNew: true,
    category: "Jackets",
  },
];

export const kidsProducts = [
  {
    id: "k1",
    name: "Technical Puffer Jacket",
    price: "39.90 USD",
    image: null,
    colors: ["#2c2c2c"],
    isNew: false,
    category: "Girl 6-14 Yrs",
  },
  {
    id: "k2",
    name: "Oversized Knit Sweater",
    price: "25.90 USD",
    image: null,
    colors: ["#f5f0e8"],
    isNew: false,
    category: "Boy 6-14 Yrs",
  },
  {
    id: "k3",
    name: "Relaxed Fit Jeans",
    price: "22.90 USD",
    image: null,
    colors: ["#3d4a5c", "#2c2c2c"],
    isNew: false,
    category: "Girl 1½-6 Yrs",
  },
  {
    id: "k4",
    name: "Leather Ankle Boots",
    price: "49.90 USD",
    image: null,
    colors: ["#2c2c2c"],
    isNew: false,
    category: "Boy 1½-6 Yrs",
  },
  {
    id: "k5",
    name: "Structured Wool Coat",
    price: "59.90 USD",
    image: null,
    colors: ["#3d4a5c", "#2c2c2c"],
    isNew: true,
    category: "Girl 6-14 Yrs",
  },
  {
    id: "k6",
    name: "Contrast Sport Set",
    price: "32.90 USD",
    image: null,
    colors: ["#2c2c2c", "#ffffff"],
    isNew: false,
    category: "Boy 6-14 Yrs",
  },
];

export const featuredProduct = {
  id: "fp1",
  name: "Linen Blend Wide Leg Trousers",
  price: "₹ 3,990",
  description: "High-waisted wide leg trousers in linen blend fabric with front pleats.",
  image: "/models/female/image copy.png",
  colors: [
    { name: "ECRU", hex: "#f5f0e8" },
    { name: "BLACK", hex: "#1a1a1a" },
    { name: "TAN", hex: "#8b6914" },
    { name: "RED", hex: "#8b1a1a" },
    { name: "CAMEL", hex: "#c4a35a" },
  ],
  sizes: ["XS", "S", "M", "L", "XL", "XXL"],
  category: "Woman",
  details: [
    "Linen blend fabric",
    "High waist with front pleats",
    "Wide leg cut",
    "Side pockets",
    "Zip and hook fastening at the side",
  ],
  care: [
    "Machine wash at 30°C gentle cycle",
    "Do not bleach",
    "Iron at medium temperature",
    "Do not tumble dry",
  ],
};
